//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waEligeTuPremio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUsuario
    {
        public int intCodigo { get; set; }
        public string vchUsuario { get; set; }
        public string vchNombre { get; set; }
        public Nullable<System.DateTime> dttmFecha { get; set; }
        public Nullable<bool> bitActivo { get; set; }
        public Nullable<int> intPerfil { get; set; }
    }
}
